class EntityConfig:

    MODULE_PATH = "alpha_recognition_quality.recognition_engine.entity.classes_lib."

    CLASSIFICATION_MAP = {  # "entity_class_name": [("file_name", "ClassName")]
        'tuchuang': [('tu_chuang', 'TuChuang')],
        'corner_window': [('zhuan_jiao_chuang', 'ZhuanJiaoChuang')],
        # 'closestool': [('bian_qi', 'BianQi'), ('da_bian_qi', 'DaBianQi'), ('zuo_bian_qi', 'ZuoBianQi')],  # TODO: 需要后续将"大便器"和"小便器"区分开
        # 'toilet': [('bian_qi', 'BianQi'), ('da_bian_qi', 'DaBianQi'), ('zuo_bian_qi', 'ZuoBianQi')],
        'check_well': [('jian_cha_jing', 'JianChaJing')],
        # 'reducing_valve': [('jian_ya_fa', 'JianYaFa')],
        'pipe': [('li_guan', 'LiGuan')],
        # 'washbasin': [('xi_mian_qi', 'XiMianQi'), ('xi_lian_pen', 'XiLianPen')],  # TODO: 目前"洗脸盆"不包含阳台中的洗脸盆，只包含卫生间的洗脸盆
        # 'sewage_sink': [('wu_shui_pen', 'WuShuiPen')],  # TODO: 目前"污水盆"包含了阳台上的洗脸盆和污水盆
        # 'shower': [('xi_yu_qi', 'XiYuQi'), ('lin_yu_qi', 'LinYuQi')],
        # 'bathtub': [('yu_pen', 'YuPen'), ("yu_gang", "YuGang")],
        # 'water_pit': [('ji_shui_keng', 'JiShuiKeng')],
        'rain_well': [('yu_shui_jing', 'YuShuiJing')],
        'stove': [('lu_zao', 'LuZao')],
        # 'alarm_valve': [('bao_jing_fa', 'BaoJingFa')],
        'distribution_box': [('pei_dian_xiang', 'PeiDianXiang')],
        # 'area_display': [('qu_yu_xian_shi_qi', 'QuYuXianShiQi')],
        # 'bus_isolator': [('zong_xian_ge_li_qi', 'ZongXianGeLiQi')],
        # 'fuse_protector': [('rong_duan_qi', 'RongDuanQi')],
        'lamp_branch': [('zhao_ming_fen_zhi_hui_lu', 'ZhaoMingFenZhiHuiLu')],
        'socket_branch': [('cha_zuo_fen_zhi_hui_lu', 'ChaZuoFenZhiHuiLu')],
        'lamp_socket_branch': [('zhao_ming_cha_zuo_fen_zhi_hui_lu', 'ZhaoMingChaZuoFenZhiHuiLu')],
        'peidianxiang_outlet_branch': [('pei_dian_xiang_chu_xian_hui_lu', 'PeiDianXiangChuXianHuiLu')],
        'weak_electric_box': [('ruo_dian_xiang', 'RuoDianXiang')],
        'strong_electric_box': [('qiang_dian_xiang', 'QiangDianXiang')],
        # 'parking': [('che_wei', 'CheWei')],
        'butterfly_valve': [('die_fa', 'DieFa')],
        'check_point': [('jian_cha_kou', 'JianChaKou')],
        'fire_button': [('shou_dong_bao_jing_an_niu', 'ShouDongBaoJingAnNiu')],
        'hydrant_button': [('xiao_huo_shuan_an_niu', 'XiaoHuoShuanAnNiu')],
        'sluice_valve': [('zha_fa', 'ZhaFa')],
        'clean_hole': [('qing_sao_kou', 'QingSaoKou')],
        'overflow_hole': [('yi_liu_kou', 'YiLiuKou')],
        'button': [('an_niu', 'AnNiu')],
        'transformer_symbols': [('bian_ya_qi_fu_hao', 'BianYaQiFuHao')],
        'indoor_stair': [('tao_nei_lou_ti', 'TaoNeiLouTi')],
        'single_stair': [('zhi_pao_lou_ti', 'ZhiPaoLouTi')],
        'double_stair': [('shuang_pao_lou_ti', 'ShuangPaoLouTi')],
        'scissors_stair': [('jian_dao_lou_ti', 'JianDaoLouTi')],
        'flow_indicator': [('shui_liu_zhi_shi_qi', 'ShuiLiuZhiShiQi')],
        'water_test_valve_end': [('mo_duan_shi_shui_fa', 'MoDuanShiShuiFa')],
        'information_socket': [('xin_xi_cha_zuo', 'XinXiChaZuo')],
        'television_socket': [('dian_shi_cha_zuo', 'DianShiChaZuo')],
        'system_sprayer': [('pen_tou_xi_tong', 'PenTouXiTong')],
        'telephone_socket': [('dian_hua_cha_zuo', 'DianHuaChaZuo')],
        'evacuation_signs': [('shu_san_zhi_shi_biao_zhi', 'ShuSanZhiShiBiaoZhi')],
        'washer': [('xi_yi_ji', 'XiYiJi')],
        'socket': [('cha_zuo', 'ChaZuo')],
        'fridge': [('bing_xiang', 'BingXiang')],
        'sprinkler': [('pen_tou', 'PenTou')],
        'phone': [('xiao_fang_dian_hua', 'XiaoFangDianHua'), ('ke_shi_dui_jiang', 'KeShiDuiJiang')],
        'broadcast': [('xiao_fang_ying_ji_guang_bo', 'XiaoFangYingJiGuangBo')],
        'limianchuang': [('li_mian_chuang', 'LiMianChuang')],
        'electricity_meter': [('dian_biao', 'DianBiao')],
        'system_alarm_valve': [('xi_tong_bao_jing_fa', 'XiTongBaoJingFa')],
        'floor_indicator_light': [('lou_ceng_biao_zhi_deng', 'LouCengBiaoZhiDeng')],
        'residual_current_circuit_breaker': [('lou_dian_duan_lu_qi', 'LouDianDuanLuQi')],
        'distribution_cabinet': [('pei_dian_gui', 'PeiDianGui')],
        'double_tube_lamp': [('shuang_guan_deng', 'ShuangGuanDeng')],
        'dilou_washmachine': [('xi_yi_ji_di_lou', 'XiYiJiDiLou')],
        'flat_switch': [('ping_mian_tu_kai_guan', 'PingMianTuKaiGuan')],
        'other_window': [('qi_ta_chuang', 'QiTaChuang')],
        'other_door': [('qi_ta_men', 'QiTaMen')],
        'sealed_door': [('mi_bi_men', 'MiBiMen')],
        'dilou': [('di_lou', 'DiLou'), ('pu_tong_di_lou', 'PuTongDiLou')],
        'fire_extinguisher': [('mie_huo_qi', 'MieHuoQi')],
        # 'water_tank': [('sheng_huo_shui_xiang', 'ShengHuoShuiXiang')],
        'casing': [('tao_guan', 'TaoGuan')],
        'fire_hydrants': [('xiao_huo_shuan', 'XiaoHuoShuan')],
        'xiaohuoshuan': [('xiao_huo_shuan', 'XiaoHuoShuan')],
        'fire_extinguisher_fire_hydrants': [('xiao_huo_shuan_he_mie_huo_qi', 'XiaoHuoShuanHeMieHuoQi')],
        'system_dilou': [('xi_tong_di_lou', 'XiTongDiLou')],
        'fire_hydrants_outdoor_siteplan': [('shi_wai_xiao_huo_shuan_zong_tu', 'ShiWaiXiaoHuoShuanZongTu')],
        'fire_hydrants_plumbing': [('xi_tong_xiao_huo_shuan', 'XiTongXiaoHuoShuan')],
        'fire_proof_door_monitor': [('fang_huo_men_jian_kong_qi', 'FangHuoMenJianKongQi')],
        'load_switch': [('fu_he_kai_guan', 'FuHeKaiGuan')],
        'surge_protector': [('lang_yong_bao_hu_qi', 'LangYongBaoHuQi')],
        'axis_mark': [('zhou_biao', 'ZhouBiao')],
        'transformer': [('bian_ya_qi', 'BianYaQi')],
        'mailbox': [('xin_bao_xiang', 'XinBaoXiang')],
        'baiye': [('bai_ye_chuang', 'BaiYeChuang'), ('bai_ye', 'BaiYe')],
        'feng_jing_bai_ye':[('feng_jing_bai_ye', 'FengJingBaiYe')],
        'window': [('pu_tong_chuang', 'PuTongChuang')],
        'temperature': [('gan_wen_tan_ce_qi', 'GanWenTanCeQi')],
        'smoke': [('gan_yan_tan_ce_qi', 'GanYanTanCeQi')],
        'menlianchuang': [('men_lian_chuang', 'MenLianChuang')],
        'light_alarm': [('sheng_guang_bao_jing_qi', 'ShengGuangBaoJingQi')],
        'emergency_lighting': [('a_xing_ying_ji_zhao_ming_deng', 'AXingYingJiZhaoMingDeng')],
        'single_tube_lamp': [('dan_guan_deng', 'DanGuanDeng')],
        'equipotential_junction_plate': [('deng_dian_wei_lian_jie_ban', 'DengDianWeiLianJieBan')],
        'kitchen_exhaust_pipe': [('chu_fang_pai_yan_guan_dao', 'ChuFangPaiYanGuanDao')],
        'elevator_box': [('dian_ti_jiao_xiang', 'DianTiJiaoXiang'), ('dian_ti', 'DianTi')],
        'famen': [('fa_men', 'FaMen')],
        'stop_valve': [('jie_zhi_fa', 'JieZhiFa')],
        'louti': [('qi_ta_lou_ti', 'QiTaLouTi')],
        'stair': [('qi_ta_lou_ti', 'QiTaLouTi')],
        'water_meter': [('shui_biao', 'ShuiBiao')],
        'rain_bucket_side': [('yu_shui_dou_ce_pai', 'YuShuiDouCePai')],
        'rain_bucket_full': [('yu_shui_dou_quan_pai', 'YuShuiDouQuanPai')],
        'intercepting_ditch': [('jie_shui_gou', 'JieShuiGou')],
        'fire_resistant_shutter_controller': [('fang_huo_juan_lian_kong_zhi_qi', 'FangHuoJuanLianKongZhiQi')],
        'juanlianmen': [('juan_lian_men', 'JuanLianMen')],
        'cd_parking': [('chong_dian_ting_che_wei', 'ChongDianTingCheWei')],
        'truck_parking': [('huo_che_ting_che_wei', 'HuoCheTingCheWei')],
        'normal_parking': [('pu_tong_ting_che_wei', 'PuTongTingCheWei')],
        'wza_parking': [('wu_zhang_ai_che_wei', 'WuZhangAiCheWei')],
        'wza_cd_parking': [('chong_dian_ting_che_wei', 'ChongDianTingCheWei'),("wu_zhang_ai_che_wei", "WuZhangAiCheWei")],
        'water_test_epuip_end_plan': [('mo_duan_shi_shui_zhuang_zhi_ping_mian', 'MoDuanShiShuiZhuangZhi_PingMian')],
        'water_test_epuip_end_system': [('mo_duan_shi_shui_zhuang_zhi_xi_tong', 'MoDuanShiShuiZhuangZhi_XiTong')],
        'contactor': [('jie_chu_qi', 'JieChuQi')],
        'thermorelay': [('re_ji_dian_qi', 'ReJiDianQi')],
        'door': [('ping_kai_men', 'PingKaiMen')],
        'elevator_door': [('dian_ti_men', 'DianTiMen')],
        'vent_cap': [('tong_qi_mao', 'TongQiMao')],
        'tuila_door': [('tui_la_men', 'TuiLaMen')],
        'pressure_meter': [('ya_li_biao', 'YaLiBiao')],
        'waste_vpipe': [('fei_shui_li_guan', 'FeiShuiLiGuan')],
        'condensate_vpipe': [('leng_ning_shui_li_guan', 'LengNingShuiLiGuan')],
        'sprinkler_vpipe': [('pen_lin_li_guan', 'PenLinLiGuan')],
        'life_supply_vpipe': [('sheng_huo_ji_shui_li_guan', 'ShengHuoJiShuiLiGuan')],
        'sewage_vpipe': [('wu_shui_li_guan', 'WuShuiLiGuan')],
        'hydrant_vpipe': [('xiao_huo_shuan_li_guan', 'XiaoHuoShuanLiGuan')],
        'rain_vpipe': [('yu_shui_li_guan', 'YuShuiLiGuan')],
        'ventilate_vpipe': [('tong_qi_li_guan', 'TongQiLiGuan')],
        'vpipe': [('qi_ta_li_guan', 'QiTaLiGuan')],
        'sink': [('xi_di_cao', 'XiDiCao'), ('xi_cai_pen', 'XiCaiPen')],
        'air_conditioner_ins': [('kong_tiao_nei_ji', 'KongTiaoNeiJi')],
        'air_conditioner_out': [('kong_tiao_wai_ji', 'KongTiaoWaiJi')],
        'switch_single': [('dan_dao_kai_guan', 'DanDaoKaiGuan')],
        'lamps': [('pu_tong_deng', 'PuTongDeng')],
        'switch_double': [('shuang_qie_kai_guan', 'ShuangQieKaiGuan')],
        'emergency_single_tube_lamp': [('ying_ji_dan_guan_deng', 'YingJiDanGuanDeng')],
        'emergency_double_tube_lamp': [('ying_ji_shuang_guan_deng', 'YingJiShuangGuanDeng')],
        'pump_connector': [('shui_beng_jie_he_qi', 'ShuiBengJieHeQi')],
        'signal_valve': [('xin_hao_fa', 'XinHaoFa')],
        'guanjingmen': [('guan_jing_men', 'GuanJingMen')],
        'light_alarm_fire_button': [('shou_dong_bao_jing_an_niu', 'ShouDongBaoJingAnNiu'),
                                    ('sheng_guang_bao_jing_qi', 'ShengGuangBaoJingQi')],
        'lamps_flat_switch': [('pu_tong_deng', 'PuTongDeng'), ('ping_mian_tu_kai_guan', 'PingMianTuKaiGuan')],
        'lamps_evacuation_signs': [('pu_tong_deng', 'PuTongDeng'), ('shu_san_zhi_shi_biao_zhi', 'ShuSanZhiShiBiaoZhi')],
        'flat_switch_evacuation_signs': [('ping_mian_tu_kai_guan', 'PingMianTuKaiGuan'),
                                         ('shu_san_zhi_shi_biao_zhi', 'ShuSanZhiShiBiaoZhi')],
        'emergency_lighting_flat_switch': [('a_xing_ying_ji_zhao_ming_deng', 'AXingYingJiZhaoMingDeng'),
                                           ('ping_mian_tu_kai_guan', 'PingMianTuKaiGuan')],
        'emergency_lighting_evacuation_signs': [('a_xing_ying_ji_zhao_ming_deng', 'AXingYingJiZhaoMingDeng'),
                                                ('shu_san_zhi_shi_biao_zhi', 'ShuSanZhiShiBiaoZhi')],
        'yinxiaxian': [('yin_xia_xian', 'YinXiaXian')],
        'elevation_window': [('pou_mian_chuang_pingmian', 'PouMianChuangPingMian')],
        'bus_isolator_smoke': [("zong_xian_ge_li_qi", "ZongXianGeLiQi"),
                               ("gan_yan_tan_ce_qi", "GanYanTanCeQi")],
        'circuit_breaker': [('duan_lu_qi', 'DuanLuQi')],
        "new_wall": [('qiang', 'Qiang')],
        'bear_wall': [("cheng_zhong_qiang", "ChengZhongQiang")],
        'no_bear_wall': [("fei_cheng_zhong_qiang", "FeiChengZhongQiang")],
        "faucet": [('faucet', "Faucet")],
        "balcony_rain_vpipe": [('yang_tai_yu_shui_li_guan', 'YangTaiYuShuiLiGuan')],
        "visual_intercom": [('ke_shi_dui_jiang', 'KeShiDuiJiang')],

        # hvac
        'fang_huo_fa_150': [('fang_huo_fa_150', 'FangHuoFa150')],
        'pai_yan_fang_huo_fa_280': [('pai_yan_fang_huo_fa_280', 'PaiYanFangHuoFa280')],
        'fang_huo_fa_70': [('fang_huo_fa_70', 'FangHuoFa70')],
        'co_tan_ce_qi': [('co_tan_ce_qi', 'COTanCeQi')],
        'xia_song_feng_kou': [('xia_song_feng_kou', 'XiaSongFengKou')],
        'ce_qiang_bu_feng_kou': [('ce_qiang_bu_feng_kou', 'CeQiangBuFengKou')],
        'ce_song_jia_ya_feng_kou': [('ce_song_jia_ya_feng_kou', 'CeSongJiaYaFengKou')],
        'ce_song_pai_yan_jian_pai_feng_kou': [('ce_song_pai_yan_jian_pai_feng_kou', 'CeSongPaiYanJianPaiFengKou')],
        'quan_re_jiao_huan_qi': [('quan_re_jiao_huan_qi', 'QuanReJiaoHuanQi')],
        'nei_chen_jin_shu_feng_guan': [('nei_chen_jin_shu_feng_guan', 'NeiChenJinShuFengGuan')],
        'fen_ti_kong_tiao': [('fen_ti_kong_tiao', 'FenTiKongTiao')],
        'fen_ji_shui_qi': [('fen_ji_shui_qi', 'FenJiShuiQi')],
        'jia_ya_feng_ji': [('jia_ya_feng_ji', 'JiaYaFengJi')],
        'ya_cha_chuan_gan_qi': [('ya_cha_chuan_gan_qi', 'YaChaChuanGanQi')],
        'bi_shi_zhou_liu_feng_ji': [('bi_shi_zhou_liu_feng_ji', 'BiShiZhouLiuFengJi'),
                                    ('ge_qiang_shi_tong_feng_qi', 'GeQiangShiTongFengQi'),
                                    ('bi_shi_pai_qi_shan', 'BiShiPaiQiShan')],
        'duo_ye_feng_kou': [('duo_ye_feng_kou', 'DuoYeFengKou')],
        'zhan_shi_pai_feng_ji': [('zhan_shi_pai_feng_ji', 'ZhanShiPaiFengJi')],
        'zhan_shi_song_feng_ji': [('zhan_shi_song_feng_ji', 'ZhanShiSongFengJi')],
        'shou_dong_kai_qi_zhuang_zhi': [('shou_dong_kai_qi_zhuang_zhi', 'ShouDongKaiQiZhuangZhi')],
        'pai_yan_jian_pai_feng_ji': [('pai_yan_jian_pai_feng_ji', 'PaiYanJianPaiFengJi')],
        'pai_yan_feng_ji': [('pai_yan_feng_ji', 'PaiYanFengJi')],
        'pai_feng_ji': [('pai_feng_ji', 'PaiFengJi')],
        'xin_feng_ji': [('xin_feng_ji', 'XinFengJi')],
        'zhi_hui_fa': [('zhi_hui_fa', 'ZhiHuiFa')],
        'mao_jin_nuan_qi_jia': [('mao_jin_nuan_qi_jia', 'MaoJinNuanQiJia')],
        'shui_guan_tao_guan': [('shui_guan_tao_guan', 'ShuiGuanTaoGuan')],
        'xie_ya_fa': [('xie_ya_fa', 'XieYaFa')],
        'xiao_sheng_qi': [('xiao_sheng_qi', 'XiaoShengQi')],
        'ran_qi_bi_gua_lu': [('ran_qi_bi_gua_lu', 'RanQiBiGuaLu')],
        'dian_dong_feng_fa': [('dian_dong_feng_fa', 'DianDongFengFa')],
        'kong_tiao_hui_feng_kou': [('kong_tiao_hui_feng_kou', 'KongTiaoHuiFengKou')],
        'you_dao_feng_ji': [('you_dao_feng_ji', 'YouDaoFengJi')],
        'song_bu_feng_ji': [('song_bu_feng_ji', 'SongBuFengJi')],
        'feng_ji_pan_guan': [('feng_ji_pan_guan', 'FengJiPanGuan')],
        'feng_guan_shang_xia_fan': [('feng_guan_shang_xia_fan', 'FengGuanShangXiaFan')],
        'emergency_exit': [('an_quan_chu_kou', 'AnQuanChuKou')],
        'bed': [('chuang', 'Chuang')],
        "reserved_hole": [('yu_liu_kong_dong', 'YuLiuKongDong'), ('qiang_dong_kou', 'QiangDongKou')],
        "reserved_hole_B": [('yu_liu_kong_dong_B', 'YuLiuKongDongB')],
        "reserved_hole_Q": [('yu_liu_kong_dong_Q', 'YuLiuKongDongQ')],
        "reserved_hole_K": [('yu_liu_kong_dong_K', 'YuLiuKongDongK')],
        "reserved_hole_P": [('yu_liu_kong_dong_P', 'YuLiuKongDongP')],
        "gutter": [('pai_shui_gou', 'PaiShuiGou')],
        "menduo": [('men_duo', 'MenDuo')],
        "paiqikou": [('pai_qi_kou', 'PaiQiKou')],
        "unequal_double_door": [('zi_mu_men', 'ZiMuMen')],
        "single_door": [('dan_kai_men', 'DanKaiMen')],
        "double_door": [('shuang_kai_men', 'ShuangKaiMen')],
        "rain_awning":[('yu_peng', 'YuPeng')],
        "air_conditioning_board":[("kong_tiao_ban_gou_jian", "KongTiaoBanGouJian")],
        "stair_rest_platform": [("lou_ti_xiu_xi_ping_tai", "LouTiXiuXiPingTai")],
        "stair_landing": [("lou_ti_lou_ceng_ping_tai", "LouTiLouCengPingTai")],
        "barrier_free_ramp": [("wu_zhang_ai_po_dao", "WuZhangAiPoDao")],
        "apron": [("san_shui", "SanShui")],
        'kitchen_cabinet': [("chu_gui", "ChuGui")],
        'lightstand': [("chuang_tou_gui", "ChuangTouGui")],
        'tv': [("dian_shi", "DianShi")],
        'heater': [("ran_qi_re_shui_qi", "RanQiReShuiQi"), ("re_shui_qi", "ReShuiQi")],
        'sofa': [("sha_fa", "ShaFa")],
        'wardrobe': [("yi_gui", "YiGui")],
        "gas_meter": [("ran_qi_biao", "RanQiBiao")],
        # decor hvac
        'air_conditioner_out': [("shi_wai_ji", "ShiWaiJi")],
        "air_conditioner_ins_pipe": [("feng_guan_shi_shi_nei_ji", "FengGuanShiShiNeiJi")],
        "air_conditioner_ins_sep": [("fen_ti_shi_shi_nei_ji", "FenTiShiShiNeiJi")],
        # "fen_ji_shui_qi": [("fen_ji_shui_qi", "FenJiShuiQi")],
        "temp_controller": [("wen_du_kong_zhi_qi", "WenDuKongZhiQi")],
        # structure
        'structure_solid_wall': [('jie_gou_qiang', 'JieGouQiang')],
        'structure_wall_column': [('jie_gou_an_zhu', 'JieGouAnZhu')],
        'structure_wall_body': [('jie_gou_qiang_shen', 'JieGouQiangShen')],
        'structure_pillar': [('jie_gou_zhu', 'JieGouZhu')],
        'structure_beam': [('jie_gou_liang', 'JieGouLiang')],
        'structure_slab': [('jie_gou_ban', 'JieGouBan')],

        # decor_architecture

    }

    COMBINATION_MAP = {  # "layer_name": [("file_name", "ClassName")]
        'elevation_handrail': [('li_mian_lan_gan', 'LiMianLanGan')],
        'dayang_handrail': [('pou_mian_lan_gan', 'PouMianLanGan')],
        'pillar': [('zhu_zi', 'ZhuZi')],
        'solid_wall_line': [('shi_xin_qiang', 'ShiXinQiang')],
        'non_solid_wall_line': [('fei_shi_xin_qiang', 'FeiShiXinQiang')],
        'dayangloutipoumiantiduan': [('da_yang_lou_ti_pou_mian_ti_duan', 'DaYangLouTiPouMianTiDuan')],
        'pillar_cap': [('zhu_mao', 'ZhuMao')],
        'plan_handrail': [('ping_mian_lan_gan', 'PingMianLanGan'), ('lan_gan', 'LanGan')],
        'elevation_window': [('pou_mian_chuang_limian', 'PouMianChuangLiMian')],
        'step': [('tai_jie', 'TaiJie')],
        'fire_resistance_wall': [('fang_huo_qiang', 'FangHuoQiang')],
        'jieshuigoupoumian': [('jie_shui_gou_pou_mian', 'JieShuiGouPouMian')],
        'floor_pavin': [('qi_pu_dian', 'QiPuDian')]
    }

    PRIMITIVE_MAP = {  # "layer_name": [("file_name", "ClassName")]
        'waste_hpipe': [('fei_shui_heng_guan', 'FeiShuiHengGuan'), ('pai_shui_heng_guan', 'PaiShuiHengGuan')],
        'jieshandai': [('jie_shan_dai', 'JieShanDai')],
        'inflow_hpipe': [('jin_shui_heng_guan', 'JinShuiHengGuan')],
        'condensate_hpipe': [('leng_ning_shui_heng_guan', 'LengNingShuiHengGuan'), ('pai_shui_heng_guan', 'PaiShuiHengGuan')],
        'cold_life_supply_hpipe': [('leng_shui_heng_guan', 'LengShuiHengGuan'), ('sheng_huo_gei_shui_heng_guan', 'ShengHuoGeiShuiHengGuan')],
        'sewage_hpipe': [('pai_shui_heng_guan', 'PaiShuiHengGuan'), ('wu_shui_heng_guan', 'WuShuiHengGuan')],
        'rain_hpipe': [('pai_shui_heng_guan', 'PaiShuiHengGuan'), ('yu_shui_heng_guan', 'YuShuiHengGuan')],
        'sprinkler_hpipe': [('pen_lin_heng_guan', 'PenLinHengGuan')],
        'hot_life_supply_hpipe': [('re_shui_heng_guan', 'ReShuiHengGuan'), ('sheng_huo_gei_shui_heng_guan', 'ShengHuoGeiShuiHengGuan')],
        'hydrant_hpipe': [('xiao_huo_shuan_heng_guan', 'XiaoHuoShuanHengGuan')],
        'rain_recycle_supply_hpipe': [('yu_shui_hui_yong_gei_shui_heng_guan', 'YuShuiHuiYongGeiShuiHengGuan')],
        'ventilate_hpipe': [('tong_qi_heng_guan', 'TongQiHengGuan')],
        'wire': [('dian_xian', 'DianXian')],
    }


class SpaceConfig:

    MODULE_PATH = "alpha_recognition_quality.recognition_engine.space.classes_lib."

    CLASS_MAP = {  # "room_chinese_name": ("file_name", "ClassName")
        '储藏室': ('chu_cang_shi', 'ChuCangShi'),
        '储藏间': ('chu_cang_jian', 'ChuCangJian'),
        '储油间': ('chu_you_jian', 'ChuYouJian'),
        '风井': ('feng_jing', 'FengJing'),
        '排风井': ('pai_feng_jing', 'PaiFengJing'),
        '公共空间': ('gong_gong_kong_jian', 'GongGongKongJian'),
        '贵重商品仓库': ('gui_zhong_shang_pin_cang_ku', 'GuiZhongShangPinCangKu'),
        '化粪池': ('hua_fen_chi', 'HuaFenChi'),
        # '基地车行出入口': ('ji_di_che_xing_chu_ru_kou', 'JiDiCheXingChuRuKou'),
        # '基地人行出入口': ('ji_di_ren_xing_chu_ru_kou', 'JiDiRenXingChuRuKou'),
        # '总图建筑轮廓': ('zong_tu_jian_zhu_lun_kuo', 'ZongTuJianZhuLunKuo'),
        # '防火分区': ('fang_huo_fen_qu', 'FangHuoFenQu'),
        '报警阀间': ('bao_jing_fa_jian', 'BaoJingFaJian'),
        '电气机房': ('dian_qi_ji_fang', 'DianQiJiFang'),
        '消防电梯机房': ('xiao_fang_dian_ti_ji_fang', 'XiaoFangDianTiJiFang'),
        '电梯机房': ('dian_ti_ji_fang', 'DianTiJiFang'),
        # '附建公共用房': ('fu_jian_gong_gong_yong_fang', 'FuJianGongGongYongFang'),
        # '商业服务网点': ('shang_ye_fu_wu_wang_dian', 'ShangYeFuWuWangDian'),
        # '文化服务中心': ('wen_hua_fu_wu_zhong_xin', 'WenHuaFuWuZhongXin'),
        # '社区服务中心': ('she_qu_fu_wu_zhong_xin', 'SheQuFuWuZhongXin'),
        # '养老服务用房': ('yang_lao_fu_wu_yong_fang', 'YangLaoFuWuYongFang'),
        # '街道办事处': ('jie_dao_ban_shi_chu', 'JieDaoBanShiChu'),
        # '总图地上水泵房': ('zong_tu_di_shang_shui_beng_fang', 'ZongTuDiShangShuiBengFang'),
        # '总图地下水泵房': ('zong_tu_di_xia_shui_beng_fang', 'ZongTuDiXiaShuiBengFang'),
        '门廊': ('men_lang', 'MenLang'),
        '外廊': ('wai_lang', 'WaiLang'),
        '通信机房': ('tong_xin_ji_fang', 'TongXinJiFang'),
        '设备用房': ('she_bei_yong_fang', 'SheBeiYongFang'),
        # '贮存食品库房': ('zhu_cun_shi_pin_ku_fang', 'ZhuCunShiPinKuFang'),
        # '库房': ('ku_fang', 'KuFang'),
        # '弧形车库坡道': ('hu_xing_che_ku_po_dao', 'HuXingCheKuPoDao'),
        # '非弧形车库坡道': ('fei_hu_xing_che_ku_po_dao', 'FeiHuXingCheKuPoDao'),
        # '车库范围': ('che_ku_fan_wei', 'CheKuFanWei'),
        # '单元出入口范围': ('dan_yuan_chu_ru_kou_fan_wei', 'DanYuanChuRuKouFanWei'),
        '大堂': ('da_tang', 'DaTang'),
        '大厅': ('da_ting', 'DaTing'),
        '门斗': ('men_dou', 'MenDou'),
        '过廊': ('guo_lang', 'GuoLang'),
        '过厅': ('guo_ting', 'GuoTing'),
        '空中花园': ('kong_zhong_hua_yuan', 'KongZhongHuaYuan'),
        '前厅': ('qian_ting', 'QianTing'),
        '电梯井': ('dian_ti_jing', 'DianTiJing'),
        '开关房': ('kai_guan_fang', 'KaiGuanFang'),
        '排烟井': ('pai_yan_jing', 'PaiYanJing'),
        '厨房油烟井': ('chu_fang_you_yan_jing', 'ChuFangYouYanJing'),
        '排烟机房': ('pai_yan_ji_fang', 'PaiYanJiFang'),
        '排风机房': ('pai_feng_ji_fang', 'PaiFengJiFang'),
        '加压机房': ('jia_ya_ji_fang', 'JiaYaJiFang'),
        '烧水间': ('shao_shui_jian', 'ShaoShuiJian'),
        # '玄关': ('xuan_guan', 'XuanGuan'),
        # '雨篷': ('yu_peng', 'YuPeng'),
        '配电箱子图': ('pei_dian_xiang_zi_tu', 'PeiDianXiangZiTu'),
        '消防风机房': ('xiao_fang_feng_ji_fang', 'XiaoFangFengJiFang'),
        '普通风机房': ('pu_tong_feng_ji_fang', 'PuTongFengJiFang'),
        '卫生间': ('wei_sheng_jian', 'WeiShengJian'),
        '公共卫生间': ('gong_gong_wei_sheng_jian', 'GongGongWeiShengJian'),
        '厨房': ('chu_fang', 'ChuFang'),
        '开放式厨房': ('kai_fang_shi_chu_fang', 'KaiFangShiChuFang'),
        '水井': ('shui_jing', 'ShuiJing'),
        '套内空间': ('tao_nei_kong_jian', 'TaoNeiKongJian'),
        '弱电机房': ('ruo_dian_ji_fang', 'RuoDianJiFang'),
        '屋面层轮廓': ('wu_mian_ceng_lun_kuo', 'WuMianCengLunKuo'),
        '消防登高场地': ('xiao_fang_deng_gao_chang_di', 'XiaoFangDengGaoChangDi'),
        '电梯前室': ('dian_ti_qian_shi', 'DianTiQianShi'),
        '发电机房': ('fa_dian_ji_fang', 'FaDianJiFang'),
        '机房': ('ji_fang', 'JiFang'),
        '热水机房': ('re_shui_ji_fang', 'ReShuiJiFang'),
        '衣帽间': ('yi_mao_jian', 'YiMaoJian'),
        # '地库轮廓': ('di_ku_lun_kuo', 'DiKuLunKuo'),
        # '用地红线轮廓': ('yong_di_hong_xian_lun_kuo', 'YongDiHongXianLunKuo'),
        # '地库坡道出入口': ('di_ku_po_dao_chu_ru_kou', 'DiKuPoDaoChuRuKou'),
        '客厅': ('ke_ting', 'KeTing'),
        '客餐厅': ('ke_can_ting', 'KeCanTing'),
        '餐厅': ('can_ting', 'CanTing'),
        '卧室': ('wo_shi', 'WoShi'),
        '阳台': ('yang_tai', 'YangTai'),
        '封闭阳台': ('feng_bi_yang_tai', 'FengBiYangTai'),
        '开敞阳台': ('kai_chang_yang_tai', 'KaiChangYangTai'),
        '设备阳台': ('she_bei_yang_tai', 'SheBeiYangTai'),
        '楼梯间': ('lou_ti_jian', 'LouTiJian'),
        '套内楼梯间': ('tao_nei_lou_ti_jian', 'TaoNeiLouTiJian'),
        '楼梯间平台': ('lou_ti_jian_ping_tai', 'LouTiJianPingTai'),
        '楼梯间楼层平台': ("lou_ti_jian_lou_ceng_ping_tai", "LouTiJianLouCengPingTai"),
        '楼梯间休息平台': ("lou_ti_jian_xiu_xi_ping_tai", "LouTiJianXiuXiPingTai"),
        '淋浴间': ('lin_yu_jian', 'LinYuJian'),
        '无障碍坡道': ('wu_zhang_ai_po_dao', 'WuZhangAiPoDao'),
        '盥洗室': ('guan_xi_shi', 'GuanXiShi'),
        '书房': ('shu_fang', 'ShuFang'),
        '连廊': ('lian_lang', 'LianLang'),
        '防烟楼梯前室': ('fang_yan_lou_ti_qian_shi', 'FangYanLouTiQianShi'),
        '生活水泵房': ('sheng_huo_shui_beng_fang', 'ShengHuoShuiBengFang'),
        '生活水箱间': ('sheng_huo_shui_xiang_jian', 'ShengHuoShuiXiangJian'),
        '变电站': ('bian_dian_zhan', 'BianDianZhan'),
        '变配电室': ('bian_pei_dian_shi', 'BianPeiDianShi'),
        '仓库': ('cang_ku', 'CangKu'),
        '食品仓库': ('shi_pin_cang_ku', 'ShiPinCangKu'),
        '地上停车场': ('di_shang_ting_che_chang', 'DiShangTingCheChang'),
        '回车场': ('hui_che_chang', 'HuiCheChang'),
        '垃圾房': ('la_ji_fang', 'LaJiFang'),
        '换热站': ('huan_re_zhan', 'HuanReZhan'),
        '配电房': ('pei_dian_fang', 'PeiDianFang'),
        '其他前室': ('qi_ta_qian_shi', 'QiTaQianShi'),
        '调压站': ('tiao_ya_zhan', 'TiaoYaZhan'),
        '消防控制室': ('xiao_fang_kong_zhi_shi', 'XiaoFangKongZhiShi'),
        '电井': ('dian_jing', 'DianJing'),
        '配电间': ('pei_dian_jian', 'PeiDianJian'),
        '强弱电井': ('qiang_ruo_dian_jing', 'QiangRuoDianJing'),
        '强电井': ('qiang_dian_jing', 'QiangDianJing'),
        '弱电井': ('ruo_dian_jing', 'RuoDianJing'),
        '设备间': ('she_bei_jian', 'SheBeiJian'),
        '电缆井': ('dian_lan_jing', 'DianLanJing'),
        '水表井': ('shui_biao_jing', 'ShuiBiaoJing'),
        '管道井': ('guan_dao_jing', 'GuanDaoJing'),
        '走廊': ('zou_lang', 'ZouLang'),
        '走道': ('zou_dao', 'ZouDao'),
        '开敞外廊': ('kai_chang_wai_lang', 'KaiChangWaiLang'),
        '封闭走廊': ('feng_bi_zou_lang', 'FengBiZouLang'),
        '天井': ('tian_jing', 'TianJing'),
        '家政间': ('jia_zheng_jian', 'JiaZhengJian'),
        '洗衣房': ('xi_yi_fang', 'XiYiFang'),
        '烟道': ('yan_dao', 'YanDao'),
        '风道': ('feng_dao', 'FengDao'),
        '入口平台': ('ru_kou_ping_tai', 'RuKouPingTai'),
        '园区普通车道': ('yuan_qu_pu_tong_che_dao', 'YuanQuPuTongCheDao'),
        '园区消防车道': ('yuan_qu_xiao_fang_che_dao', 'YuanQuXiaoFangCheDao'),
        '套内水管井': ('tao_nei_shui_guan_jing', 'TaoNeiShuiGuanJing'),
        '合用前室': ('he_yong_qian_shi', 'HeYongQianShi'),
        '锅炉房': ('guo_lu_fang', 'GuoLuFang'),
        '避难间': ('bi_nan_jian', 'BiNanJian'),
        '消防水泵房': ('xiao_fang_shui_beng_fang', 'XiaoFangShuiBengFang'),
        '消防水箱间': ('xiao_fang_shui_xiang_jian', 'XiaoFangShuiXiangJian'),
        '泵房': ('beng_fang', 'BengFang'),
        '露台': ('lu_tai', 'LuTai'),
        '平面图建筑轮廓': ('ping_mian_tu_jian_zhu_lun_kuo', 'PingMianTuJianZhuLunKuo'),
        '空调板': ('kong_tiao_ban', 'KongTiaoBan'),
        '空调机位': ('kong_tiao_ji_wei', 'KongTiaoJiWei'),
        '太阳能板位': ('tai_yang_neng_ban_wei', 'TaiYangNengBanWei'),
        '消防电梯井': ('xiao_fang_dian_ti_jing', 'XiaoFangDianTiJing'),
        '消防电梯前室': ('xiao_fang_dian_ti_qian_shi', 'XiaoFangDianTiQianShi'),
        '接闪器': ('jie_shan_qi', 'JieShanQi'),
        '电信间': ('dian_xin_jian', 'DianXinJian'),
        "强电间": ('qiang_dian_jian', 'QiangDianJian'),
        "弱电间": ('ruo_dian_jian', 'RuoDianJian'),
        '设备平台': ('she_bei_ping_tai', 'SheBeiPingTai'),
        '接线间': ('jie_xian_jian', 'JieXianJian'),
        '屋面': ('wu_mian', 'WuMian'),
        '工具间': ('gong_ju_jian', 'GongJuJian'),
        '热计量间': ('re_ji_liang_jian', 'ReJiLiangJian'),
        '水暖井': ('shui_nuan_jing', 'ShuiNuanJing'),
        '暖井': ('nuan_jing', 'NuanJing'),
        '电表井': ('dian_biao_jing', 'DianBiaoJing'),
        '空调机房': ('kong_tiao_ji_fang', 'KongTiaoJiFang'),
        '凹廊': ("ao_lang", "AoLang"),
        '独立前室': ("du_li_qian_shi", "DuLiQianShi"),
        '卫生间干区': ("wei_sheng_jian_gan_qu", "WeiShengJianGanQu"),
        '无名称空间': ("wu_ming_cheng_kong_jian", "WuMingChengKongJian"),
        '大堂屋面': ("da_tang_wu_mian", "DaTangWuMian"),
        '电梯厅': ("dian_ti_ting", "DianTiTing"),
        '飘窗': ("piao_chuang", "PiaoChuang"),
        '封闭楼梯间': ("feng_bi_lou_ti_jian", "FengBiLouTiJian"),
        '防烟楼梯间': ("fang_yan_lou_ti_jian", "FangYanLouTiJian"),
        '剪刀楼梯间': ("jian_dao_lou_ti_jian", "JianDaoLouTiJian"),
        '敞开楼梯间': ("chang_kai_lou_ti_jian", "ChangKaiLouTiJian"),
        '卫生间排风井': ("wei_sheng_jian_pai_feng_jing", "WeiShengJianPaiFengJing"),
        '三合一前室': ("san_he_yi_qian_shi", "SanHeYiQianShi"),
        '共用前室': ("gong_yong_qian_shi", "GongYongQianShi"),
        '扩大独立前室': ("kuo_da_du_li_qian_shi", "KuoDaDuLiQianShi"),
        '扩大合用前室': ("kuo_da_he_yong_qian_shi", "KuoDaHeYongQianShi"),
        '主卧': ("zhu_wo", "ZhuWo"),
        '次卧': ("ci_wo", "CiWo"),
        '其他卧室': ("qi_ta_wo_shi", "QiTaWoShi"),
        '信报间': ("xin_bao_jian", "XinBaoJian"),
        '清洁间': ("qing_jie_jian", "QingJieJian"),
        '新风管': ("xin_feng_guan", "XinFengGuan"),
        '排风管': ("pai_feng_guan", "PaiFengGuan"),
        '非机动车坡道': ("fei_ji_dong_che_po_dao", "FeiJiDongChePoDao"),
        '非机动车坡道休息平台': ("fei_ji_dong_che_po_dao_xiu_xi_ping_tai", "FeiJiDongChePoDaoXiuXiPingTai"),
        '公区设备平台': ("gong_qu_she_bei_ping_tai", "GongQuSheBeiPingTai"),
        '户内设备平台': ("hu_nei_she_bei_ping_tai", "HuNeiSheBeiPingTai"),
        '扩大三合一前室': ("kuo_da_san_he_yi_qian_shi", "KuoDaSanHeYiQianShi"),
        '扩大消防电梯前室': ("kuo_da_xiao_fang_dian_ti_qian_shi", "KuoDaXiaoFangDianTiQianShi"),
        '扩大封闭楼梯间': ("kuo_da_feng_bi_lou_ti_jian", "KuoDaFengBiLouTiJian"),
        '上人屋面': ("shang_ren_wu_mian", "ShangRenWuMian")
    }


# class MarkConfig:
#
#     MODULE_PATH = "recognition_engine.mark.classes_lib."
#
#     CLASS_MAP = {  # class_name: ("file_name", "ClassName")
#         "arrow": ("jiantou", "JianTou"),
#         "red_line": ("yongdihongxian", "YongDiHongXian"),
#         "finish_surface": ("wanchengmian", "WanChengMian"),
#         "wall": ("qiangxian", "QiangXian"),
#         "annotation": ("yinzhu", "YinZhu"),
#
#         # 张劲松负责
#         "yuanquchurukou": ("yuanquchurukou", "YuanQuChuRuKou"),
#         "chufangcaozuotaibianxian": ("chufangcaozuotaibianxian", "ChuFangCaoZuoTaiBianXian"),
#
#         # 吴磊彬负责
#         # "elevation_symbol": ("biaogaofuhao", "BiaoGaoFuHao"),
#         # "": ("dixiachekuchedaoxian", "DiXiaCheKuCheDaoXian"),  # 地下车库车道线
#     }
